project:
  type: website
  output-dir: docs

website:
  title: "Learning Web Security - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sql-injection.qmd
      - authentication.qmd
      - directory-traversal.qmd
      - command-injection.qmd
      - business-logic-vulnerabilities.qmd
      - information-disclosure.qmd
      - access-control.qmd
      - file-upload-vulnerabilities.qmd
      - server-side-request-forgery.qmd
      - xxe-injection.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
